### Sever
server:
  port: ${SERVER_PORT:8080}

### Spring
spring:
  application:
    name: transaction-simulation-test-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/transaction-simulation-test-db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migrations
    enabled: true

### Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method

### Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com:
      example: TRACE

### Actuator
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### Information
info:
  app:
    name: "transaction-simulation-test-service"
    description: "Transaction simulation test service"
  author: "Edinei Gonçalves"
  java-version: ${java.version}
